# Generated by Django 6.0.2 on 2026-02-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("HOLD", "Hold")],
                        default="HOLD",
                        max_length=4,
                    ),
                ),
                ("confidence", models.FloatField(help_text="Confidence score 0-100")),
                (
                    "indicators",
                    models.JSONField(
                        default=dict, help_text="Individual indicator values and contributions"
                    ),
                ),
                ("reasoning", models.TextField(blank=True, help_text="Human-readable explanation")),
                ("executed", models.BooleanField(default=False)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="core.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal",
                "verbose_name_plural": "Signals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4),
                ),
                ("entry_price", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "exit_price",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
                ),
                ("quantity", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "pnl",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
                ),
                ("pnl_percent", models.FloatField(blank=True, null=True)),
                ("is_simulated", models.BooleanField(default=False)),
                ("order_id", models.CharField(blank=True, max_length=100)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="trading.signal",
                    ),
                ),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="core.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade",
                "verbose_name_plural": "Trades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["trading_pair", "-created_at"], name="trading_sig_trading_a33dc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["direction", "-created_at"], name="trading_sig_directi_3dcfd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["executed", "-created_at"], name="trading_sig_execute_2ca44c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["trading_pair", "-created_at"], name="trading_tra_trading_a32f40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["is_simulated", "-created_at"], name="trading_tra_is_simu_039c5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(fields=["side", "-created_at"], name="trading_tra_side_d6583f_idx"),
        ),
    ]
