# Generated by Django 6.0.2 on 2026-02-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_fk'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who owns this trade', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'trading_pair', '-created_at'], name='trading_tra_user_id_180227_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'is_simulated', '-created_at'], name='trading_tra_user_id_a522f6_idx'),
        ),
    ]
