# Generated by Django 5.2.11 on 2026-02-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_bot_last_synced_at_bot_triggered_by_signal'),
        ('trading', '0003_make_user_fk_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalAccuracyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_days', models.IntegerField(default=30)),
                ('total_executed_signals', models.IntegerField(default=0)),
                ('profitable_signals', models.IntegerField(default=0)),
                ('unprofitable_signals', models.IntegerField(default=0)),
                ('overall_accuracy', models.FloatField(default=0.0)),
                ('buy_accuracy', models.FloatField(default=0.0)),
                ('sell_accuracy', models.FloatField(default=0.0)),
                ('confidence_correlation', models.FloatField(null=True)),
                ('average_pnl_percent', models.FloatField(null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_accuracy_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal Accuracy Metrics',
                'verbose_name_plural': 'Signal Accuracy Metrics',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['user', '-calculated_at'], name='trading_sig_user_id_375bee_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_pnl', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('final_pnl_percent', models.FloatField(null=True)),
                ('is_profitable', models.BooleanField(null=True)),
                ('bot_duration_hours', models.FloatField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_outcomes', to='bots.bot')),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='trading.signal')),
            ],
            options={
                'verbose_name': 'Signal Outcome',
                'verbose_name_plural': 'Signal Outcomes',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['is_profitable', '-recorded_at'], name='trading_sig_is_prof_dc8a11_idx')],
            },
        ),
    ]
