# Generated by Django 5.2.11 on 2026-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_signalaccuracymetrics_signaloutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='context_scores',
            field=models.JSONField(blank=True, help_text='Dict of composite context scores', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='recommended_bot_type',
            field=models.CharField(blank=True, help_text='Context-recommended bot type (GRID/DCA/NONE)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='regime',
            field=models.CharField(blank=True, help_text='Market regime at time of signal', max_length=20, null=True),
        ),
    ]
