# Generated by Django 5.2.11 on 2026-02-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_add_context_fields_to_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_combination', models.JSONField(help_text="Dict of feature names to value ranges that define this pattern. Example: {'regime': 'TRENDING_UP', 'rsi_range': [30, 50], 'adx_min': 25}")),
                ('sample_size', models.IntegerField(help_text='Number of signals evaluated for this pattern')),
                ('average_pnl', models.FloatField(help_text='Average P&L percentage for signals matching this pattern')),
                ('hit_rate', models.FloatField(help_text='Fraction of profitable signals (0.0-1.0)')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='When this pattern was discovered')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pattern is currently used for recommendations')),
            ],
            options={
                'verbose_name': 'Strategy Pattern',
                'verbose_name_plural': 'Strategy Patterns',
                'ordering': ['-hit_rate', '-average_pnl'],
                'indexes': [models.Index(fields=['is_active', '-hit_rate'], name='trading_str_is_acti_ba9797_idx'), models.Index(fields=['-discovered_at'], name='trading_str_discove_d2ec70_idx')],
            },
        ),
    ]
