# Generated by Django 6.0.2 on 2026-02-04 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('encrypted_api_secret', models.TextField(blank=True, default='')),
                ('api_key_salt', models.CharField(blank=True, default='', max_length=64)),
                ('default_trading_mode', models.CharField(choices=[('dry_run', 'Dry Run (Simulation)'), ('live', 'Live Trading')], default='dry_run', max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('notification_email_enabled', models.BooleanField(default=True)),
                ('active_trading_pairs', models.JSONField(blank=True, default=list, help_text='List of trading pair symbols the user is interested in')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
