# Generated by Django 6.0.2 on 2026-02-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who owns this portfolio snapshot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['user', 'is_simulated', '-created_at'], name='core_portfo_user_id_5b03fd_idx'),
        ),
    ]
