# Generated by Django 5.2.11 on 2026-02-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSentimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fear_greed_index', models.IntegerField(null=True)),
                ('fear_greed_classification', models.CharField(blank=True, max_length=20)),
                ('funding_rates', models.JSONField(default=dict)),
                ('liquidation_volume_24h', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('liquidation_long_percent', models.FloatField(null=True)),
                ('liquidation_short_percent', models.FloatField(null=True)),
                ('open_interest', models.JSONField(default=dict)),
                ('btc_dominance', models.FloatField(null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Sentiment Data',
                'verbose_name_plural': 'Market Sentiment Data',
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
    ]
