# Generated by Django 5.2.11 on 2026-02-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marketsentimentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(blank=True, db_index=True, help_text='Trading pair symbol (nullable for global metrics)', max_length=20, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the snapshot was taken')),
                ('btc_dominance', models.FloatField(blank=True, help_text='BTC dominance percentage', null=True)),
                ('global_market_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Total crypto market cap in USD', max_digits=20, null=True)),
                ('total_volume_24h', models.DecimalField(blank=True, decimal_places=2, help_text='24h total crypto volume in USD', max_digits=20, null=True)),
                ('active_addresses', models.IntegerField(blank=True, help_text='Active address count', null=True)),
                ('net_exchange_flow', models.FloatField(blank=True, help_text='Net exchange flow (inflow minus outflow)', null=True)),
                ('whale_tx_count', models.IntegerField(blank=True, help_text='Whale transaction count (>$100k)', null=True)),
                ('defi_tvl', models.DecimalField(blank=True, decimal_places=2, help_text='Total DeFi TVL', max_digits=20, null=True)),
                ('social_sentiment_score', models.FloatField(blank=True, help_text='Social sentiment polarity (-1.0 to 1.0)', null=True)),
                ('social_mention_count', models.IntegerField(blank=True, help_text='Social mention count', null=True)),
                ('social_buzz_score', models.FloatField(blank=True, help_text='Social buzz score', null=True)),
                ('fear_greed_index', models.IntegerField(blank=True, help_text='Fear & Greed Index (0-100)', null=True)),
                ('is_stale', models.BooleanField(default=False, help_text='True if any data source failed')),
                ('stale_fields', models.JSONField(blank=True, default=list, help_text='List of field names with stale data')),
                ('regime', models.CharField(blank=True, db_index=True, help_text='Detected regime label', max_length=20, null=True)),
                ('trend_strength_score', models.FloatField(blank=True, help_text='Composite trend strength score (0.0-1.0)', null=True)),
                ('risk_regime_score', models.FloatField(blank=True, help_text='Composite risk regime score (0.0-1.0)', null=True)),
                ('sentiment_regime_score', models.FloatField(blank=True, help_text='Composite sentiment regime score (0.0-1.0)', null=True)),
                ('is_degraded', models.BooleanField(default=False, help_text='True if any input was stale')),
            ],
            options={
                'verbose_name': 'Market Context Snapshot',
                'verbose_name_plural': 'Market Context Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='core_market_symbol_357727_idx'), models.Index(fields=['regime', '-timestamp'], name='core_market_regime_7360e4_idx')],
            },
        ),
    ]
