# Generated by Django 5.2.11 on 2026-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_marketcontextsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_onchain_api_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_social_api_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onchain_api_key_salt',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_api_key_salt',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
