# Generated by Django 6.0.2 on 2026-02-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pionex_bot_id", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "bot_type",
                    models.CharField(
                        choices=[
                            ("GRID", "Grid Bot"),
                            ("DCA", "DCA Bot"),
                            ("INFINITY_GRID", "Infinity Grid Bot"),
                            ("FUTURES_GRID", "Futures Grid Bot"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("STOPPED", "Stopped"),
                            ("ERROR", "Error"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("invested_amount", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "current_value",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "current_pnl",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("pnl_percent", models.FloatField(blank=True, null=True)),
                ("params", models.JSONField(default=dict, help_text="Bot-specific parameters")),
                ("is_simulated", models.BooleanField(default=False)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("stop_reason", models.TextField(blank=True)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bots",
                        to="core.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot",
                "verbose_name_plural": "Bots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("STARTED", "Started"),
                            ("MODIFIED", "Modified"),
                            ("STOPPED", "Stopped"),
                            ("ERROR", "Error"),
                            ("PERFORMANCE_UPDATE", "Performance Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("reasoning", models.TextField(blank=True, help_text="Why this action was taken")),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Event",
                "verbose_name_plural": "Bot Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bot",
            index=models.Index(fields=["status", "-created_at"], name="bots_bot_status_aef2a4_idx"),
        ),
        migrations.AddIndex(
            model_name="bot",
            index=models.Index(
                fields=["bot_type", "-created_at"], name="bots_bot_bot_typ_72679e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bot",
            index=models.Index(
                fields=["trading_pair", "-created_at"], name="bots_bot_trading_a4d3d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bot",
            index=models.Index(
                fields=["is_simulated", "status"], name="bots_bot_is_simu_583fbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botevent",
            index=models.Index(fields=["bot", "-created_at"], name="bots_boteve_bot_id_1ff265_idx"),
        ),
        migrations.AddIndex(
            model_name="botevent",
            index=models.Index(
                fields=["event_type", "-created_at"], name="bots_boteve_event_t_687182_idx"
            ),
        ),
    ]
