# Generated by Django 6.0.2 on 2026-02-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('core', '0003_add_user_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who owns this bot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['user', 'status', '-created_at'], name='bots_bot_user_id_6975d9_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['user', 'trading_pair', '-created_at'], name='bots_bot_user_id_c3b469_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['user', 'is_simulated', 'status'], name='bots_bot_user_id_d6b618_idx'),
        ),
    ]
