# Generated by Django 5.2.11 on 2026-02-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_make_user_fk_required'),
        ('trading', '0003_make_user_fk_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time bot data was synced from Pionex', null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='triggered_by_signal',
            field=models.ForeignKey(blank=True, help_text='The signal that triggered this bot creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_bots', to='trading.signal'),
        ),
    ]
