"""Trading models for signals and trades."""

from datetime import timedelta
from decimal import Decimal

from django.db import models
from django.db.models import Avg, Count, QuerySet, Sum
from django.utils import timezone

from apps.core.models import TimeStampedModel, TradingPair


class SignalDirection(models.TextChoices):
    """Trading signal direction."""

    BUY = "BUY", "Buy"
    SELL = "SELL", "Sell"
    HOLD = "HOLD", "Hold"


class SignalQuerySet(QuerySet):
    """Custom QuerySet for Signal model with common filtering methods."""

    def recent(self, hours: int = 24) -> "SignalQuerySet":
        """Return signals from the last N hours."""
        cutoff = timezone.now() - timedelta(hours=hours)
        return self.filter(created_at__gte=cutoff)

    def by_direction(self, direction: str) -> "SignalQuerySet":
        """Filter signals by direction."""
        return self.filter(direction=direction)

    def buy_signals(self) -> "SignalQuerySet":
        """Return only BUY signals."""
        return self.filter(direction=SignalDirection.BUY)

    def sell_signals(self) -> "SignalQuerySet":
        """Return only SELL signals."""
        return self.filter(direction=SignalDirection.SELL)

    def actionable(self) -> "SignalQuerySet":
        """Return BUY or SELL signals (not HOLD)."""
        return self.exclude(direction=SignalDirection.HOLD)

    def high_confidence(self, threshold: float = 85.0) -> "SignalQuerySet":
        """Return signals with confidence above threshold."""
        return self.filter(confidence__gte=threshold)

    def executed(self) -> "SignalQuerySet":
        """Return only executed signals."""
        return self.filter(executed=True)

    def pending(self) -> "SignalQuerySet":
        """Return signals not yet executed."""
        return self.filter(executed=False)

    def for_pair(self, symbol: str) -> "SignalQuerySet":
        """Filter signals for a specific trading pair."""
        return self.filter(trading_pair__symbol=symbol)

    def average_confidence(self) -> float:
        """Calculate average confidence across signals."""
        result = self.aggregate(avg=Avg("confidence"))
        return result["avg"] or 0.0


class SignalManager(models.Manager):
    """Custom manager for Signal model."""

    def get_queryset(self) -> SignalQuerySet:
        """Return custom queryset."""
        return SignalQuerySet(self.model, using=self._db)

    def recent(self, hours: int = 24) -> SignalQuerySet:
        """Get recent signals."""
        return self.get_queryset().recent(hours)

    def actionable_recent(self, hours: int = 24) -> SignalQuerySet:
        """Get recent actionable (BUY/SELL) signals."""
        return self.get_queryset().recent(hours).actionable()

    def high_confidence_recent(
        self, hours: int = 24, threshold: float = 85.0
    ) -> SignalQuerySet:
        """Get recent high-confidence signals."""
        return self.get_queryset().recent(hours).high_confidence(threshold)

    def for_pair(self, symbol: str) -> SignalQuerySet:
        """Get all signals for a trading pair."""
        return self.get_queryset().for_pair(symbol)

    def latest_for_pair(self, symbol: str):
        """Get the most recent signal for a trading pair."""
        return self.get_queryset().for_pair(symbol).first()


class Signal(TimeStampedModel):
    """
    Trading signal generated by market analysis.

    Contains direction, confidence score, and all contributing indicators.
    """

    trading_pair = models.ForeignKey(
        TradingPair,
        on_delete=models.CASCADE,
        related_name="signals",
    )
    direction = models.CharField(
        max_length=4,
        choices=SignalDirection.choices,
        default=SignalDirection.HOLD,
    )
    confidence = models.FloatField(help_text="Confidence score 0-100")
    indicators = models.JSONField(
        default=dict,
        help_text="Individual indicator values and contributions",
    )
    reasoning = models.TextField(blank=True, help_text="Human-readable explanation")
    executed = models.BooleanField(default=False)
    executed_at = models.DateTimeField(null=True, blank=True)

    objects = SignalManager()

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Signal"
        verbose_name_plural = "Signals"
        indexes = [
            models.Index(fields=["trading_pair", "-created_at"]),
            models.Index(fields=["direction", "-created_at"]),
            models.Index(fields=["executed", "-created_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.trading_pair.symbol} {self.direction} ({self.confidence:.1f}%)"


class TradeSide(models.TextChoices):
    """Trade side (buy or sell)."""

    BUY = "BUY", "Buy"
    SELL = "SELL", "Sell"


class TradeQuerySet(QuerySet):
    """Custom QuerySet for Trade model with common filtering methods."""

    def recent(self, hours: int = 24) -> "TradeQuerySet":
        """Return trades from the last N hours."""
        cutoff = timezone.now() - timedelta(hours=hours)
        return self.filter(created_at__gte=cutoff)

    def live(self) -> "TradeQuerySet":
        """Return only live (non-simulated) trades."""
        return self.filter(is_simulated=False)

    def simulated(self) -> "TradeQuerySet":
        """Return only simulated trades."""
        return self.filter(is_simulated=True)

    def buys(self) -> "TradeQuerySet":
        """Return only buy trades."""
        return self.filter(side=TradeSide.BUY)

    def sells(self) -> "TradeQuerySet":
        """Return only sell trades."""
        return self.filter(side=TradeSide.SELL)

    def open_positions(self) -> "TradeQuerySet":
        """Return trades without exit price (open positions)."""
        return self.filter(exit_price__isnull=True)

    def closed(self) -> "TradeQuerySet":
        """Return closed trades (with exit price)."""
        return self.filter(exit_price__isnull=False)

    def profitable(self) -> "TradeQuerySet":
        """Return trades with positive P&L."""
        return self.filter(pnl__gt=0)

    def unprofitable(self) -> "TradeQuerySet":
        """Return trades with negative P&L."""
        return self.filter(pnl__lt=0)

    def for_pair(self, symbol: str) -> "TradeQuerySet":
        """Filter trades for a specific trading pair."""
        return self.filter(trading_pair__symbol=symbol)

    def in_date_range(self, start_date, end_date) -> "TradeQuerySet":
        """Filter trades within a date range."""
        return self.filter(created_at__gte=start_date, created_at__lte=end_date)

    def total_pnl(self) -> Decimal:
        """Calculate total P&L across all trades in queryset."""
        result = self.aggregate(total=Sum("pnl"))
        return result["total"] or Decimal("0")

    def total_volume(self) -> Decimal:
        """Calculate total trading volume (quantity * entry_price)."""
        from django.db.models import F

        result = self.aggregate(total=Sum(F("quantity") * F("entry_price")))
        return result["total"] or Decimal("0")

    def win_rate(self) -> float:
        """Calculate win rate (profitable trades / total closed trades)."""
        closed = self.closed()
        total = closed.count()
        if total == 0:
            return 0.0
        winners = closed.profitable().count()
        return (winners / total) * 100

    def statistics(self) -> dict:
        """Get comprehensive trade statistics."""
        closed = self.closed()
        return {
            "total_trades": self.count(),
            "open_positions": self.open_positions().count(),
            "closed_trades": closed.count(),
            "profitable_trades": closed.profitable().count(),
            "unprofitable_trades": closed.unprofitable().count(),
            "total_pnl": self.total_pnl(),
            "win_rate": self.win_rate(),
        }


class TradeManager(models.Manager):
    """Custom manager for Trade model."""

    def get_queryset(self) -> TradeQuerySet:
        """Return custom queryset."""
        return TradeQuerySet(self.model, using=self._db)

    def recent(self, hours: int = 24) -> TradeQuerySet:
        """Get recent trades."""
        return self.get_queryset().recent(hours)

    def live(self) -> TradeQuerySet:
        """Get live trades only."""
        return self.get_queryset().live()

    def simulated(self) -> TradeQuerySet:
        """Get simulated trades only."""
        return self.get_queryset().simulated()

    def open_positions(self, simulated: bool = False) -> TradeQuerySet:
        """Get open positions."""
        qs = self.get_queryset().open_positions()
        return qs.simulated() if simulated else qs.live()

    def for_pair(self, symbol: str) -> TradeQuerySet:
        """Get all trades for a trading pair."""
        return self.get_queryset().for_pair(symbol)

    def history(
        self, simulated: bool = False, limit: int = 100
    ) -> TradeQuerySet:
        """Get trade history with optional limit."""
        qs = self.get_queryset().closed()
        qs = qs.simulated() if simulated else qs.live()
        return qs[:limit]

    def statistics(self, simulated: bool = False) -> dict:
        """Get trade statistics."""
        qs = self.get_queryset()
        qs = qs.simulated() if simulated else qs.live()
        return qs.statistics()


class Trade(TimeStampedModel):
    """
    Record of an executed trade.

    Can be linked to a signal and/or bot. Tracks entry, exit, and P&L.
    """

    signal = models.ForeignKey(
        Signal,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="trades",
    )
    trading_pair = models.ForeignKey(
        TradingPair,
        on_delete=models.CASCADE,
        related_name="trades",
    )
    side = models.CharField(max_length=4, choices=TradeSide.choices)
    entry_price = models.DecimalField(max_digits=20, decimal_places=10)
    exit_price = models.DecimalField(max_digits=20, decimal_places=10, null=True, blank=True)
    quantity = models.DecimalField(max_digits=20, decimal_places=10)
    pnl = models.DecimalField(max_digits=20, decimal_places=10, null=True, blank=True)
    pnl_percent = models.FloatField(null=True, blank=True)
    is_simulated = models.BooleanField(default=False)
    order_id = models.CharField(max_length=100, blank=True)
    closed_at = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(blank=True)

    objects = TradeManager()

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Trade"
        verbose_name_plural = "Trades"
        indexes = [
            models.Index(fields=["trading_pair", "-created_at"]),
            models.Index(fields=["is_simulated", "-created_at"]),
            models.Index(fields=["side", "-created_at"]),
        ]

    def __str__(self) -> str:
        status = "simulated" if self.is_simulated else "live"
        return f"{self.side} {self.quantity} {self.trading_pair.symbol} @ {self.entry_price} ({status})"
